'use client'
import './../styles/globals.css'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux';
import { Toaster } from 'react-hot-toast';
import { configureStore } from '@reduxjs/toolkit';
import rootReducer from '@/redux/rootReducer/rootReducer';

const inter = Inter({ subsets: ['latin'] })

const store = configureStore({
  reducer: rootReducer,
});

// export const metadata = {
//   title: 'Stream AI Music',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Provider store={store}>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  )
}
